languageCode = "en-us"
relativeURLs = false
sectionPagesMenu = "main"

title = "Angelo Carly"
theme = "hello-friend"

[menu]
    [[menu.main]]
        identifier = "whois"
        name = "Whois"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2

     [[menu.main]]
        identifier = "cv"
        name = "CV"
        url = "https://raw.githubusercontent.com/angelocarly/CV/master/cv.pdf"
        weight = 3



[params]
  title = "Angelo Carly"
  description = "Personal site and blog"
  baseURL = "https://magnias.dev/"

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Magnias dev"
    subtitle = "Personal devlog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "magnias"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
