languageCode = "en-us"
relativeURLs = true
sectionPagesMenu = "main"
baseURL = "https://magnias.dev"

title = "Angelo Carly"
theme = "hello-friend"
disqusShortname = "magnias-dev"

[params]
  title = "Magnias"
  description = "Personal site and blog"
  baseURL = "https://magnias.dev/"
  fullWidthTheme = false
  centerTheme = true

  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Magnias dev"
    subtitle = "Personal devlog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "magnias"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Whois"
        url = "/"
		weight = 2
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
		weight = 3
