languageCode = "en-us"
relativeURLs = true
sectionPagesMenu = "main"

title = "Angelo Carly"
theme = "mag"

[menu]
    [[menu.main]]
        identifier = "whois"
        name = "Whois"
        url = "/"
        weight = 100

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 110



[params]
	title = "Angelo Carly"
	description = "Personal site and blog"
	baseURL = "https://magnias.be/"
