languageCode = "en-us"
relativeURLs = false
sectionPagesMenu = "main"

title = "Angelo Carly"
theme = "mag"

[menu]
    [[menu.main]]
        identifier = "whois"
        name = "Whois"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2

     [[menu.main]]
        identifier = "cv"
        name = "CV"
        url = "https://raw.githubusercontent.com/angelocarly/CV/master/cv.pdf"
        weight = 3



[params]
	title = "Angelo Carly"
	description = "Personal site and blog"
	baseURL = "https://magnias.be/"
